os: osx
osx_image: xcode11.5
language: swift
script: xcodebuild clean build test -project Surveys_Feature/Surveys_Feature.xcodeproj -scheme "Survey Feature CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
